slug: docker-001-3
spec: dual-node
repo: github.com/Kyuubang/vagrant-sample

start:
  - echo "this running from start"

grade:
  - name: check docker-compose installed on node1
    on: node1
    script: if command -v docker-compose >/dev/null 2>&1; then echo "installed"; else echo "not installed"; fi
    expect: installed

  - name: check docker-compose not installed on node2
    on: node2
    script: if command -v docker-compose >/dev/null 2>&1; then echo "installed"; else echo "not installed"; fi
    expect: not installed

finish:
  - echo "hello bro finished"
